### PR TITLE
fix: grep mode not working with git_files

### LINKED ISSUE #4: Grep mode returns no results when toggling from git_files
## Bug Description

When using `Seeker git_files` mode, toggling to grep mode with `<C-e>` results in no search results, regardless of the search query. However, `Seeker files` mode works correctly.

## Steps to Reproduce

1. Open Neovim in a git repository
2. Run `:Seeker git_files`
3. Filter files by typing a keyword (e.g., "lua")
4. Press `<C-e>` to toggle to grep mode
5. Type any search query
6. **Expected**: Search results from filtered files
7. **Actual**: No results appear

## Root Cause

There are two issues in `lua/seeker/backends/snacks.lua`:

### Issue 1: Incorrect use of `glob` parameter

In `create_grep_picker()` function (line 134-140), the code passes file paths to `picker_opts.glob`:

```lua
if #file_list > 0 then
    local relative_paths = {}
    for _, file in ipairs(file_list) do
        table.insert(relative_paths, vim.fn.fnamemodify(file, ':~:.'))
    end
    picker_opts.glob = relative_paths  -- Wrong!
end
```

However, snacks.nvim's `glob` parameter expects glob patterns (like `*.lua`), not file paths. The correct parameter is `dirs` for specifying a list of files to search.

### Issue 2: Incorrect path construction

In `toggle_to_grep()` function (line 18), the code uses `utils.extract_file_paths()` which doesn't account for the `item.cwd` field. When snacks picker returns items from `git_files`, the `item.file` is relative to `item.cwd`, not the current working directory.

For example:
- `item.cwd` = `/Users/user/dotfiles`
- `item.file` = `nvim/ftplugin/lua.lua`
- Current working directory = `/Users/user/dotfiles/nvim`

When using `vim.fn.fnamemodify(file, ':p')` on the relative path, it results in incorrect paths like `/Users/user/dotfiles/nvim/nvim/ftplugin/lua.lua` (duplicated `nvim`).

## Environment

- Neovim version: [your version]
- seeker.nvim version: latest (commit d4d8bf9)
- picker_provider: snacks

## Additional Context

The issue only affects `git_files` mode because snacks.nvim's `git_files` picker returns items with a different `cwd` than the current working directory, while `files` picker typically uses the current directory as `cwd`.

### PR DESCRIPTION
**Pull request by edte**
## Description

Fix grep mode not working when toggling from `git_files` mode.

Fixes #4

### 1. Fix path construction in `toggle_to_grep()`

Replace the use of `utils.extract_file_paths()` with manual path extraction that properly handles `item.cwd`:

- Extract file paths directly from picker items
- Use `item.cwd` (if available) to correctly construct absolute paths
- This ensures paths are correct regardless of the current working directory

### 2. Use `dirs` parameter instead of `glob` in `create_grep_picker()`

- Change from `picker_opts.glob = relative_paths` to `picker_opts.dirs = file_list`
- The `dirs` parameter is the correct way to specify a list of files for snacks.nvim's grep
- The `glob` parameter is meant for glob patterns (like `*.lua`), not file paths

## Testing

Tested with the following workflow:

1. Run `:Seeker git_files` in a git repository
2. Filter files by typing "lua"
3. Press `<C-e>` to toggle to grep mode
4. Search for "vim"
5. **Before**: No results
6. **After**: Correctly shows search results from filtered lua files

Also verified that:
- `Seeker files` mode continues to work correctly
- Toggling back to file mode with `<C-e>` works as expected
- Multi-selection with `<Tab>` still functions properly

## Related Issues

This bug only affected `git_files` mode because snacks.nvim's git_files picker returns items with `cwd` set to the git root, which may differ from the current working directory.

### CODE REVIEW

File: lua/seeker/backends/snacks.lua [hunk 1]
```diff
@@ -15,7 +15,23 @@ local function toggle_to_grep(picker)
         return
     end
 
-    local file_paths = utils.extract_file_paths(items)
+    -- Extract file paths and convert to absolute paths using item.cwd
```
Comment (2KAbhishek) [inline lua/seeker/backends/snacks.lua:18]: we can skip the comments

**Comment by 2KAbhishek** [comment]
@edte thanks for the PR, some minor comments above to resolve

can you also please add tests to cover this scenario

**Comment by 2KAbhishek** [comment]
actually let me take care of those after merging, thanks again :)
